repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        # NOTE https://github.com/pre-commit/pre-commit/issues/3133
        additional_dependencies:
          - prettier@3.5.0 # renovate: datasource=npm
          - prettier-plugin-svelte@^3.3.3 # renovate: datasource=npm
          - prettier-plugin-astro@^0.14.1 # renovate: datasource=npm
        files: \.(astro|svelte|mdx|md|yml|yaml)$
