name: Generate images for docs
on:
  workflow_dispatch:
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # Use @nf-core-bot token to check out so we can push without a PR
          token: ${{ secrets.NF_CORE_BOT_AUTH_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.x

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@561fcfc7146dcb12e3871909b635ab092a781f34 # v2

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1

      - name: Install nf-core/tools
        run: pip install nf-core

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@8ce988cc253c240a3027ba58e33e47640935dd8b # v1
        env:
          COLUMNS: 100
          HIDE_PROGRESS: 'true'
          NXF_ANSI_LOG: false
        with:
          commit_changes: 'true'
          terminal_width: 100
          skip_git_checks: 'true'
          search_include: '.github/workflows/rich-codex.yml'
